# Generated by Django 4.1.2 on 2022-11-04 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('foto_vehiculo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('estado', models.BooleanField(default=True)),
                ('id_conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_referencia', models.CharField(max_length=20)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Marca_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=20)),
                ('id_referencia_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.referencia_vehiculo')),
            ],
        ),
    ]
