# Generated by Django 4.1.2 on 2022-11-04 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('cc', models.CharField(max_length=20)),
                ('foto_persona', models.ImageField(blank=True, null=True, upload_to='media')),
                ('telefono', models.CharField(max_length=20)),
                ('referido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona')),
            ],
        ),
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=20)),
                ('foto_licencia', models.ImageField(blank=True, null=True, upload_to='media')),
                ('foto_conductor', models.ImageField(blank=True, null=True, upload_to='media')),
                ('estado', models.BooleanField(default=True)),
                ('antecedentes', models.CharField(blank=True, max_length=100, null=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona')),
            ],
        ),
    ]
