# Generated by Django 4.0.5 on 2022-11-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('cc', models.CharField(max_length=20)),
                ('foto_persona', models.ImageField(blank=True, null=True, upload_to='media')),
                ('telefono', models.CharField(max_length=20)),
                ('referido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona')),
            ],
        ),
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('licencia', models.CharField(max_length=20)),
                ('foto_licencia', models.ImageField(blank=True, null=True, upload_to='media')),
                ('foto_conductor', models.ImageField(blank=True, null=True, upload_to='media')),
                ('estado', models.BooleanField(default=True)),
                ('antecedentes', models.CharField(blank=True, max_length=100, null=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona')),
            ],
        ),
    ]
