# Generated by Django 4.1.2 on 2022-11-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
